apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
      - name: backend-app
        env:
          - name: REDIS_HOST
            value: redis
