apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
  template:
    metadata:
    spec:
      containers:
      - name: backend-app
        image: nightknighto/semicolon-backend:v1-prod
        command: ["npm", "run", "deploy-linux"]
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        ports:
        - containerPort: 3000
      initContainers:
      - name: backend-test-app # This container is used to run tests before the main container starts
        image: nightknighto/semicolon-backend:v1-base
        command: ["npm", "run", "test"]
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
      
