apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app
  - db

# Transformers
namePrefix: semicolon-

commonLabels:
  app: semicolon
  type: backend

# Generators
configMapGenerator:
  - name: app-config
    literals:
      - PORT='3000'
      - DEV_DB_URL='mongodb://semicolon-backend-db:27017/semicolon-dev?directConnection=true'
      - TEST_DB_URL='mongodb://semicolon-backend-db:27017/semicolon-test?directConnection=true'
      - PROD_DB_URL='mongodb://semicolon-backend-db:27017/semicolon-prod?directConnection=true'
  
  - name: db-config
    literals:
      - MONGODB_REPLICA_SET_MODE='primary'
      - ALLOW_EMPTY_PASSWORD='yes'
      
secretGenerator:
  - name: app-secret
    literals:
      - PROD_SESSION_SECRET=dummy
      - SESSION_SECRET=dummy
